### ISSUE TITLE
Problems with deployment

### ISSUE THREAD

**Issue by Norbiros** [31-LO/31-lo-site#17]
When I open an invalid url (for example `/test`) on my local machine, our website returns nice 404 page:
![Screenshot from 2024-04-15 20-39-45](https://github.com/31-LO/31-lo-site/assets/89837724/98c0638f-979f-43f6-ae6e-107547ccda1f)
But [https://www.lo31.krakow.pl/test](https://www.lo31.krakow.pl/test) returns:
![image](https://github.com/31-LO/31-lo-site/assets/89837724/4dd8043c-0bf9-40fa-bf83-eab4dcf217cf)
And [https://www.lo31.krakow.pl/docs/](https://www.lo31.krakow.pl/docs/) returns:
![image](https://github.com/31-LO/31-lo-site/assets/89837724/eedd7730-554e-40bd-9e3d-b01580b2d187)
IMO, this is problem with production deployment configuration...

**Comment by pensjonatus** [comment]
It is a problem with deployment. I'll see if I can find settings for this.

**Comment by pensjonatus** [comment]
I changed the server settings:
1. Set deployment to emit files with a trailing slash
2. Added error pages to .htaccess
