### ISSUE TITLE
Add information about Child Protection Standards

### ISSUE THREAD

**Issue by Norbiros** [31-LO/31-lo-site#18]
By August 15, 2024, it will be a legal requirement for all schools in Poland to include information about the "[Standardy Ochrony Małoletnich](https://standardy.fdds.pl/)" on their websites.

You can find more information about it [here](https://standardy.fdds.pl/upload/upload2/podrecznik-standardy-ochrony-dzieci-w-zlobkach-i-placowkach-oswiatowych-pdf-1692962147-1-9.pdf), especially:

> Ogłoszenie następuje w sposób dostępny dla pracowników placówki, dzieci i ich opiekunów,
> w szczególności poprzez wywieszenie w miejscu ogłoszeń dla pracowników lub poprzez
> przesłanie jej tekstu drogą elektroniczną oraz poprzez zamieszczenie na stronie interne-
> towej i wywieszenie w widocznym miejscu w siedzibie, również w wersji skróconej, prze-
> znaczonej dla dzieci.

**Comment by pensjonatus** [comment]
Thanks. Krakow authorities will issue a common document for all schools to use. When they send it, we will add it.

**Comment by pensjonatus** [comment]
Done!
