### ISSUE TITLE
Cookie consent background color

### ISSUE THREAD

**Issue by Norbiros** [31-LO/31-lo-site#8]
Color of cookies popup is manually set in: https://github.com/31-LO/31-lo-site/blob/23dd0a73169b02b85fda5a76e9394a7a5f697296/src/components/CookieDialog/CookieDialog.module.css#L5
Because of that, it looks bad in dark mode:
![image](https://github.com/31-LO/31-lo-site/assets/89837724/04322a32-6168-48dd-a5be-6c8d41043bc2)

**Comment by pensjonatus** [comment]
Thanks for spotting this, @Norbiros
